### ISSUE TITLE
Multi federation

### ISSUE THREAD

**Issue by benthecarman** [HarborWallet/harbor#55]
We have support in the backend, just need to expose the functions based on the federation id.

After we have that functionality we need the ability to transfer between the two

**Comment by EthnTuttle** [comment]
![image](https://github.com/MutinyWallet/harbor/assets/133234413/d0d6ba23-aa74-4dc9-8bbc-37a115d327bd)
This may or may not be caught in impl for this but I was able to add two of the same federation. Mainly because I'm click happy and impatient.

**Comment by EthnTuttle** [comment]
Glad to see this closed. Is there again dev on harbor?!?
