### ISSUE TITLE
justfile has incorrect db cleanup

### ISSUE THREAD

**Issue by futurepaul** [HarborWallet/harbor#98]
@benthecarman I've been wondering about this command, is it right as the default used is `~/.harbor` ?

_Originally posted by @oleonardolima in https://github.com/HarborWallet/harbor/pull/97#discussion_r1825019870_

I think the correct behavior is just to `rm -f ~/.harbor/signet/harbor.sqlite`?

**Comment by benthecarman** [comment]
the command is just meant for resetting the db for tests, not for running in dev
